name: Publish dev images to quay.io

on:
  workflow_call:
    inputs:
      tag:
        type: string
        default: quay.io/gingersnap/db-syncer:latest

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        run: mvn package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Image and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/main/docker/Dockerfile.jvm
          tags: ${{ inputs.tag }}
          outputs: type=docker,dest=/tmp/db-syncer.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: db-syncer
          path: /tmp/db-syncer.tar

