name: Publish dev images to quay.io

on:
  push:
    branches:
      - 'main'

jobs:
  image:
    uses: ryanemerson/db-syncer/.github/workflows/build-image.yaml@gh_action_image_build

  upload:
    needs: image
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          # TODO can we use the output of the image job to ascertain this?
          name: db-syncer
          path: /tmp

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Load and Push image
        # Use same tag value as passed to image job
        run: |
        docker load --input /tmp/db-syncer.tar
        docker push quay.io/gingersnap/db-syncer:latest
